### ISSUE TITLE
Error: minimal bridge amount is 37 DAI

### ISSUE THREAD

**Issue by Flouse** [Magickbase/force-bridge#6]
## Testnet 
https://testnet.forcebridge.com/bridge/Ethereum/Nervos?xchain-asset=0x9D4b99b866910E9647d5f8D35CCAbFc91c0A501F

![image](https://user-images.githubusercontent.com/1297478/215031178-d5c167ca-5516-4d15-ac79-2f44761d5946.png)
I want to bridge 100 DAI, but it failed.

`Error: minimal bridge amount is 37 DAI` was disabling the bridge button.

**Comment by pygman** [comment]
![image](https://user-images.githubusercontent.com/7877698/217242081-66596072-3939-42e1-a668-5e2972508ca9.png)

I bridged 101 DAI and it worked. 
The bridge button was not disable by `Error: minimal bridge amount is 37 DAI`,  when you enter 101 in the amount box, you typed 1 and then 0 and then 1, it checks that 1 and 10 are less than 37, the console will throw an error,  this error can be ignored. 
The bridge button may be disabled due to your local network or metamask popup dialog being minimized or something else.

**Comment by Flouse** [comment]
> The bridge button may be disabled due to your local network or metamask popup dialog being minimized or something else.

I see, thank you.
